module: Swiftarr
module_version: 0.1
title: Swiftarr - The v3 Twitarr server
author: The Twitarr Team
# author_url:
github_url: https://github.com/jocosocial/swiftarr
github_file_prefix: https://github.com/jocosocial/swiftarr/tree/master
# copyright:

swift_version: 5.6

theme: fullwidth
skip_undocumented: no
hide_documentation_coverage: no
# head:

documentation: docs/Swiftarr/*.md
abstract: docs/Swiftarr/Sections/*.md

min_acl: private

custom_categories:
  - name: Overview
    children:
      - Contributing
      - Development
      - Roadmap
      - Special Files
      - Documentation

  - name: Operations
    children:
      - Configuration
      - MacOS Installation
      - Linux Installation
      - Docker Installation
      - Database Migration
      - Deployment

  - name: Twitarr API
    children:
      - Pitch
      - API Overview
      - Canonical Links
      - API Changelist

  - name: Controllers
    children:
    - AdminController
    - AlertController
    - AuthController
    - BoardgameController
    - ClientController
    - EventController
    - FezController
    - ForumController
    - ImageController
    - KaraokeController
    - ModerationController
    - TestController
    - TwitarrController
    - UserController
    - UsersController

  - name: Models
    children:
    - AlertWord
    - Announcement
    - Boardgame
    - Category
    - DailyTheme
    - Event
    - FezPost
    - ForumEdit
    - ForumPostEdit
    - ForumPost
    - Forum
    - FriendlyFezEdit
    - FriendlyFez
    - KaraokePlayedSong
    - KaraokeSong
    - ModeratorAction
    - MuteWord
    - ProfileEdit
    - RegistrationCode
    - Report
    - Token
    - TwarrtEdit
    - Twarrt
    - UserNote
    - User
    
  - name: Enumerations
    children:
    - BarrelType
    - EventType
    - FezType
    - ImageHandlerType
    - LikeType
    - ReportType
    - UserAccessLevel

  - name: Request Structs
    children:
    - BarrelCreateData
    - EventsUpdateData
    - FezContentData
    - ForumCreateData
    - ImageUploadData
    - NoteCreateData
    - NoteUpdateData
    - PostContentData
    - PostCreateData
    - ProfileEditData
    - ReportData
    - UserCreateData
    - UserPasswordData
    - UserRecoveryData
    - UserUsernameData
    - UserVerifyData
    
  - name: Return Structs
    children:
    - AddedUserData
    - AlertKeywordData
    - BarrelData
    - BarrelListData
    - BlockedUserData
    - CategoryData
    - CreatedNoteData
    - CreatedUserData
    - CurrentUserData
    - EventData
    - FezData
    - FezDetailData
    - FezPostData
    - ForumData
    - ForumListData
    - MuteKeywordData
    - MutedUserData
    - NoteData
    - NoteEditData
    - PostData
    - PostDetailData
    - ProfilePublicData
    - SeaMonkey
    - TokenStringData
    - TwarrtData
    - TwarrtDetailData
    - UploadedImageData
    - UserHeader
    - UserInfo
    - UserProfileData
    - UserSearch
    
  - name: Extensions
    children:
    - CharacterSet
    - Date
    - Formatter
    - Future
    - ISO8601DateFormatter
    - JSONDecoder
    - JSONEncoder
    - RouteCollection
    - String
    
  - name: Migrations
    children:
    - AdminUser
    - Categories
    - ClientUsers
    - EventForums
    - Events
    - Forums
    - RegistrationCodes
    - TestUsers

  - name: Pivots
    children:
    - PostLikes
    - TwarrtLikes
    
  - name: Protocols
    children:
    - ContentFilterable
    - ImageHandler
    - UserBookmarkable
    - UserTaggable
    
  - name: Internal Structs/Classes
    children:
    - EventParser
    - ForumEdit
    - ProfileEdit
    - Settings
    - TwarrtEdit
    
