module: App
module_version: 0.1
title: swiftarr 0.1.0
author: grundoon
# author_url:
github_url: https://github.com/grundoon/swiftarr
github_file_prefix: https://github.com/grundoon/swiftarr/tree/master
# copyright:

swift_version: 5.1.2

theme: fullwidth
skip_undocumented: no
hide_documentation_coverage: no
# head:

min_acl: private

custom_categories:
  - name: Models
    children:
    - Barrel
    - Event
    - RegistrationCode
    - Report
    - Token
    - User
    - UserNote
    - UserProfile
    
  - name: Controllers
    children:
    - AdminController
    - AuthController
    - ClientController
    - EventController
    - TestController
    - UserController
    - UsersController

  - name: Enumerations
    children:
    - BarrelType
    - EventType
    - ReportType
    - UserAccessLevel

  - name: Extensions
    children:
    - CharacterSet
    - Future
    - RouteCollection
    
  - name: Migrations
    children:
    - AdminUser
    - ClientUsers
    - Events
    - RegistrationCodes
    - TestUsers
    
  - name: Request Structs
    children:
    - BarrelCreateData
    - EventsUpdateData
    - NoteCreateData
    - NoteUpdateData
    - UserCreateData
    - UserPasswordData
    - UserProfileData
    - UserRecoveryData
    - UserReportData
    - UserUsernameData
    - UserVerifyData
    
  - name: Return Structs
    children:
    - AddedUserData
    - AlertKeywordData
    - BarrelData
    - BarrelListData
    - BlockedUserData
    - CreatedNoteData
    - CreatedUserData
    - CurrentUserData
    - EventData
    - MuteKeywordData
    - MutedUserData
    - SeaMonkey
    - NoteData
    - TokenStringData
    - UserHeader
    - UserInfo
    - UserSearch
    
  - name: Internal Structs/Classes
    children:
    - EventParser
    - ProfileEdit
    
