module: App
module_version: 0.1
title: swiftarr 0.1.0
author: grundoon
# author_url:
github_url: https://github.com/grundoon/swiftarr
github_file_prefix: https://github.com/grundoon/swiftarr/tree/master
# copyright:

swift_version: 5.1.2

theme: fullwidth
skip_undocumented: no
hide_documentation_coverage: no
# head:

min_acl: private

custom_categories:
  - name: Models
    children:
    - Barrel
    - Category
    - Event
    - Forum
    - ForumPost
    - RegistrationCode
    - Report
    - Token
    - User
    - UserNote
    - UserProfile
    
  - name: Controllers
    children:
    - AdminController
    - AuthController
    - ClientController
    - EventController
    - ForumController
    - TestController
    - UserController
    - UsersController

  - name: Enumerations
    children:
    - BarrelType
    - EventType
    - ImageHandlerType
    - ReportType
    - UserAccessLevel

  - name: Extensions
    children:
    - CharacterSet
    - Future
    - RouteCollection
    
  - name: Migrations
    children:
    - AdminUser
    - Categories
    - ClientUsers
    - Events
    - Forums
    - RegistrationCodes
    - TestUsers
    
  - name: Protocols
    children:
    - ImageHandler
    
  - name: Request Structs
    children:
    - BarrelCreateData
    - EventsUpdateData
    - ForumCreateData
    - ImageUploadData
    - NoteCreateData
    - NoteUpdateData
    - UserCreateData
    - UserPasswordData
    - UserProfileData
    - UserRecoveryData
    - UserReportData
    - UserUsernameData
    - UserVerifyData
    
  - name: Return Structs
    children:
    - AddedUserData
    - AlertKeywordData
    - BarrelData
    - BarrelListData
    - BlockedUserData
    - CategoryData
    - CreatedNoteData
    - CreatedUserData
    - CurrentUserData
    - EventData
    - ForumData
    - ForumListData
    - ForumPostData
    - MuteKeywordData
    - MutedUserData
    - SeaMonkey
    - NoteData
    - TokenStringData
    - UploadedImageData
    - UserHeader
    - UserInfo
    - UserSearch
    
  - name: Internal Structs/Classes
    children:
    - EventParser
    - ProfileEdit
    
