groups:
  - name: host
    rules:
      - alert: TestAlert
        expr: 1
        for: 1m
        labels:
          severity: page
        annotations:
          seamail.twitarr.com/participants: admin,twitarrteam
