global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 10s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["host.docker.internal:9093"]

scrape_configs:
  - job_name: "swiftarr"
    metrics_path: /api/v3/client/metrics
    basic_auth: 
      username: prometheus
      password: password 
    static_configs:
      - targets: ["host.docker.internal:8081"]