version: '3'
services:
  swiftarr:
    build:
      context: ..
      dockerfile: scripts/Dockerfile.linux-testing
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
    volumes:
      # This is needed since "Private Swiftarr Config" is listed in the .dockerignore file.
      - ../Sources/Run/Private Swiftarr Config:/swiftarr/Sources/Run/Private Swiftarr Config:ro

  postgres:
    image: docker.io/bitnami/postgresql:14
    environment:
      POSTGRESQL_DATABASE: swiftarr-test
      POSTGRESQL_USERNAME: swiftarr
      POSTGRESQL_PASSWORD: password

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
