version: '3'
services:
  postgres:
    image: docker.io/library/postgres:14.1
    environment:
      POSTGRES_DB: swiftarr
      POSTGRES_USER: swiftarr
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:6.2.6-alpine

  web:
    build:
      context: ..
      dockerfile: scripts/Dockerfile.production
      args:
        env: production
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_DB: swiftarr
      DATABASE_USER: swiftarr
      DATABASE_PASSWORD: password
      REDIS_HOSTNAME: redis
      WAIT_HOSTS: postgres:5432,redis:6379
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
      WAIT_HOST_CONNECT_TIMEOUT: 10
    volumes:
      - images:/app/images

volumes:
  images:
  pgdata:
