version: '3'
services:
  postgres:
    image: docker.io/library/postgres:14.1
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:6.2.6-alpine

  web:
    build:
      context: ..
      dockerfile: scripts/Dockerfile.stack
      args:
        # We always build the image in production mode.
        env: production
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOSTNAME: redis
      WAIT_HOSTS: postgres:5432,redis:6379
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
      WAIT_HOST_CONNECT_TIMEOUT: 10
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - images:/app/images

volumes:
  images:
  pgdata:
