version: '3'
services:
  postgres:
    image: docker.io/bitnami/postgresql:14
    env_file:
      - "../Sources/Run/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - pgdata:/bitnami/postgresql

  redis:
    image: docker.io/bitnami/redis:6.2
    env_file:
      - "../Sources/Run/Private Swiftarr Config/${ENVIRONMENT}.env"

  web:
    build:
      context: ..
      dockerfile: scripts/Dockerfile.stack
      args:
        # We always build the image in production mode.
        env: production
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - redis
    env_file:
      - "../Sources/Run/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - images:/app/images

volumes:
  images:
  pgdata:
