version: '3'
services:

  postgres:
    image: docker.io/bitnami/postgresql:14
    environment:
      POSTGRESQL_DATABASE: swiftarr
      POSTGRESQL_USERNAME: swiftarr
      POSTGRESQL_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: docker.io/bitnami/redis:6.2
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  prometheus:
    image: docker.io/bitnami/prometheus:2.32.1
    ports:
      - 9090:9090
    volumes:
      - ../Prometheus/swiftarr.yml:/opt/bitnami/prometheus/conf/swiftarr.yml:ro
      - ../Prometheus/alerts.yml:/opt/bitnami/prometheus/conf/alerts.yml:ro
    command:
      - '--web.enable-admin-api'
      - '--config.file=/opt/bitnami/prometheus/conf/swiftarr.yml'

  alertmanager:
    image: docker.io/bitnami/alertmanager:0.23.0
    ports:
      - 9093:9093
    volumes:
      - ../Prometheus/alertmanager.yml:/opt/bitnami/alertmanager/conf/config.yml:ro