version: '3'
services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: swiftarr
      POSTGRES_USER: swiftarr
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  postgres-test:
    image: postgres
    container_name: postgres-test
    environment:
      POSTGRES_DB: swiftarr-test
      POSTGRES_USER: swiftarr
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

  redis-test:
    image: redis:alpine
    container_name: redis-test
    ports:
      - 6380:6379
