version: '3'
services:
  postgres:
    image: docker.io/library/postgres:14.1
    env_file:
      - "../Sources/Run/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:6.2.6-alpine
    env_file:
      - "../Sources/Run/Private Swiftarr Config/${ENVIRONMENT}.env"

  web:
    build:
      context: ..
      dockerfile: scripts/Dockerfile.stack
      args:
        # We always build the image in production mode.
        env: production
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - redis
    env_file:
      - "../Sources/Run/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - images:/app/images

volumes:
  images:
  pgdata:
