version: '3'
services:

  postgres:
    image: docker.io/ubuntu/postgres:14-22.04_beta
    user: postgres
    env_file:
      - "../Sources/App/seeds/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: docker.io/ubuntu/redis:6.0-22.04_beta
    user: redis
    env_file:
      - "../Sources/App/seeds/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - redisdata:/data

  web:
    build:
      context: ..
      dockerfile: scripts/Dockerfile.stack
      args:
        # We always build the image in production mode.
        env: production
    ports:
      - ${SWIFTARR_PORT}:${SWIFTARR_PORT}
    depends_on:
      - postgres
      - redis
    env_file:
      - "../Sources/App/seeds/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - "../Sources/App/seeds:/app/swiftarr_App.resources/seeds:ro"
      - images:/app/images

volumes:
  images:
  pgdata:
  redisdata:
