version: '3'
services:

  postgres:
    image: docker.io/library/postgres:14.1
    environment:
      POSTGRES_DB: swiftarr
      POSTGRES_USER: swiftarr
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: docker.io/library/redis:6.2.6-alpine
    ports:
      - 6379:6379
