version: '3'
services:

  postgres:
    image: docker.io/bitnami/postgresql:14
    environment:
      POSTGRESQL_DATABASE: swiftarr
      POSTGRESQL_USERNAME: swiftarr
      POSTGRESQL_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: docker.io/bitnami/redis:6.2
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
