version: '3'
services:
  swiftarr:
    build:
      context: ..
      dockerfile: scripts/Dockerfile.linux-testing
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379

  postgres:
    image: docker.io/library/postgres:14.1
    environment:
      POSTGRES_DB: swiftarr-test
      POSTGRES_USER: swiftarr
      POSTGRES_PASSWORD: password

  redis:
    image: docker.io/library/redis:6.2.6-alpine
