version: '3'
services:

  postgres:
    image: docker.io/ubuntu/postgres:14-22.04_beta
    user: postgres
    environment:
      POSTGRES_DB: swiftarr
      POSTGRES_USER: swiftarr
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: docker.io/ubuntu/redis:6.0-22.04_beta
    user: redis
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  prometheus:
    image: docker.io/ubuntu/prometheus:2.20-20.04_beta
    # 2.20-20.04_beta does not support custom user yet :(
    # user: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./Prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    command:
      - '--web.enable-admin-api'
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: docker.io/ubuntu/prometheus-alertmanager:0.23-22.04_beta
    user: nobody
    ports:
      - 9093:9093
    volumes:
      - ./Prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
