name: PublishDocumentation
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  publish:
    if: github.repository == 'jocosocial/swiftarr'
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Publish Jazzy Docs
      uses: jocosocial/publish-jazzy-docs@v2.1
      with:
        personal_access_token: ${{ secrets.DOCS_ACCESS_TOKEN }}
        config: .jazzy.yaml
